import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Game from '../components/Game'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
 
  const [ init, setInit ] = useState(false);

  useEffect(() => {}, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        { init && <Game /> }
        <button onClick={() => setInit(i => !i)}>Start Game</button>
      </div>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
